Title = "Leamprov"
baseURL = "http://www.leamprov.com/"
languageCode = "en-us"
theme = "Casper"
title = "Leamprov"
[deployment]
order = [".jpg$", ".gif$"]
[[deployment.targets]]
URL = "s3://www.leamprov.com?region=eu-west-2"
name = "AWS"
[params]
description = "Leamington Spa Improvised Comedy"
facebook = "https://facebook.com"
github = "https://github.com/jonathanjanssens"
logo = "uploads/leamprovlogo.jpg"
mainSections = ["post"]
twitter = "https://twitter.com"
[privacy.instagram]
disabled = false
simple = true
[privacy.twitter]
disabled = false
enableDNT = true
simple = true
[privacy.vimeo]
disabled = false
simple = true
[privacy.youtube]
disabled = false
privacyEnhanced = true
[services.instagram]
disableInlineCSS = true
[services.twitter]
disableInlineCSS = true
[taxonomies]
category = "categories"
series = "series"
tag = "tags"
